### ISSUE TITLE
Constanly rebooting on ESP32

### ISSUE THREAD

**Issue by GrillinGorilla** [DominikN/ESP32_ledstrip_webserver#1]
Hi there, thanks for building this and publishing this tutorial. I followed the instructions and I am experiencing my device constantly rebooting. This is the log output, from the Serial Monitor, which repeats about twice a second. It seems a file is missing from the cache? Do you have any thoughts to resolve it? Thanks for your time.

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:956
load:0x40078000,len:0
load:0x40078000,len:13076
entry 0x40078a58
[0;32mI (282) heap_init: Initializing. RAM available for dynamic allocation:[0m
[0;32mI (283) heap_init: At 3FFAE6E0 len 00011920 (70 KiB): DRAM[0m
[0;32mI (285) heap_init: At 3FFC9630 len 000169D0 (90 KiB): DRAM[0m
[0;32mI (291) heap_init: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM[0m
[0;32mI (297) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM[0m
[0;32mI (303) heap_init: At 40091A44 len 0000E5BC (57 KiB): IRAM[0m
assertion "false && "item should have been present in cache"" failed: file "/build/esp-idf/components/nvs_flash/src/nvs_item_hash_list.cpp", line 85, function: void nvs::HashList::erase(size_t)
abort() was called at PC 0x400dfa73 on core 0

Backtrace: 0x40088004:0x3ffb20d0 0x40088103:0x3ffb20f0 0x400dfa73:0x3ffb2110 0x400e540c:0x3ffb2140 0x400e4906:0x3ffb2160 0x400e4be1:0x3ffb21a0 0x400e3f40:0x3ffb21f0 0x400e3b3a:0x3ffb2240 0x400e3bc3:0x3ffb2260 0x400e3bee:0x3ffb2280 0x400d4148:0x3ffb22a0 0x4011eb0b:0x3ffb22c0 0x400e1c9a:0x3ffb22f0

Rebooting...

**Comment by sourabhmisal** [comment]
Same issue , any views on how to overcome it? @GrillinGorilla @DominikN

**Comment by DominikN** [comment]
I have just refactored a project and migrated it to PlatformIO. GitHub Actions workflow also added to make sure project is building fine. Closing issue.
